version: '3.4'

services:
  kmedoids1:
    image: kmedoids
    command: dotnet KMedoids.dll ForContainers ${x1} ${x2}
    volumes:
      - D:/volume:/app/data

  kmedoids2:
    image: kmedoids
    command: dotnet KMedoids.dll ForContainers ${x2} ${x3}
    volumes:
       - D:/volume:/app/data

  kmedoids3:
    image: kmedoids
    command: dotnet KMedoids.dll ForContainers ${x3} ${x4}
    volumes:
      - D:/volume:/app/data
volumes:
  my-volume: